[project]
name = "kimep-intranet-proxy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "flask>=3.1.3",
    "ipython>=9.10.0",
    "jupyter>=1.1.1",
    "requests>=2.32.5",
]
